<svg xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     class="<?php echo $this->getData('class'); ?>"
     width="<?php echo $this->getData('width'); ?>"
     height="<?php echo $this->getData('height'); ?>"
     viewBox="<?php echo $this->getData('viewBox'); ?>"
>
    <defs>
        <path id="icons-default-qr"
              d="M 17.29 18.62 v -1.33 h -3.99 v -3.99 h 3.99 v 2.66 h 2.66 v 2.66 h -1.33 v 2.66 h -2.66 v 2.66 h -2.66 v -3.99 h 2.66 v -1.33 h 1.33 Z m 6.65 5.32 h -5.32 v -2.66 h 2.66 v -2.66 h 2.66 v 5.32 Z M 0 0 h 10.64 v 10.64 H 0 V 0 Z m 2.66 2.66 v 5.32 h 5.32 V 2.66 H 2.66 Z m 10.64 -2.66 h 10.64 v 10.64 h -10.64 V 0 Z m 2.66 2.66 v 5.32 h 5.32 V 2.66 h -5.32 Z M 0 13.3 h 10.64 v 10.64 H 0 v -10.64 Z m 2.66 2.66 v 5.32 h 5.32 v -5.32 H 2.66 Z m 17.29 -2.66 h 3.99 v 2.66 h -3.99 v -2.66 Z M 3.99 3.99 h 2.66 v 2.66 H 3.99 V 3.99 Z m 0 13.3 h 2.66 v 2.66 H 3.99 v -2.66 Z M 17.29 3.99 h 2.66 v 2.66 h -2.66 V 3.99 Z"
        >
        </path>
    </defs>
    <use xlink:href="#icons-default-qr"></use>
</svg>
